[phases.setup]
nixPkgs = ["nodejs-18_x", "python311"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip setuptools wheel",
  "python3 -m pip install -r requirements.txt"
]

[start]
cmd = "node app.js"

