[phases.setup]
nixPkgs = ["nodejs-18_x", "python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmds = [
  "npm install",
  "python3 -m venv venv",
  "source venv/bin/activate",
  "pip install --upgrade pip setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "node app.js"

